pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        IMAGE_NAME = "karthikeyaapp"
        VERSION = "1"
        FULL_IMAGE_NAME = "%DOCKERHUB_CREDENTIALS_USR%/%IMAGE_NAME%:%VERSION%"
    }

    stages {
        stage('Build') {
            steps {
                bat 'docker build -t vskartdocker/karthikapp:3.0 .'
            }
        }
       
        stage('Push') {
            steps {
                bat 'docker push vskartdocker/karthikapp:3.0'
            }
        }
    }
    
}
