pipeline {
    agent any

    stages {
        stage('Build and Deploy') {
            steps {
                sh 'sudo docker build -t praneethkaliki/praneethapp:V1ec2AL2 .'          
            }
        }
    }
}
