pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        IMAGE_NAME = "teamapp"
        VERSION = "haripriya"
        FULL_IMAGE_NAME = "$DOCKERHUB_CREDENTIALS_USR/$IMAGE_NAME:$VERSION"
    }

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t $FULL_IMAGE_NAME docker/teamapp/'          
            }
        }
        stage('Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push') {
            steps {
                sh 'docker push $FULL_IMAGE_NAME'
            }
        }
        stage('Remove') {
            steps {
                sh 'docker rmi $FULL_IMAGE_NAME'
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}
